import type {Metadata} from "next";
import {inter} from "@/app/_assets/fonts";
import MuiThemeProvider from "@/app/providers/mui-provider";


export const metadata: Metadata = {
    title: 'AI Paraphrasing Tool',
    description: "Generated by AI Paraphrasing Tool",
    icons: {
        icon: [
            {url: '/favicon.ico', type: 'image/x-icon'},
            {url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png'},
            {url: '/favicon.svg', type: 'image/svg+xml'},
        ],
        apple: [
            {url: '/apple-touch-icon.png', sizes: '180x180'},
        ],
    },
    manifest: '/site.webmanifest',
    appleWebApp: {
        title: 'AI Paraphrasing Tool',
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <MuiThemeProvider>
            {children}
        </MuiThemeProvider>
        </body>
        </html>
    );
}
