import type {Metadata} from "next";
import MuiThemeProvider from "@/providers/mui-provider";
import {inter} from "@/theme/fonts";

export const metadata: Metadata = {
    title: 'AI Paraphrasing Tool',
    description: "Generated by AI Paraphrasing Tool",
    icons: {
        icon: [
            {url: '/favicon.ico', type: 'image/x-icon'},
            {url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png'},
            {url: '/favicon.svg', type: 'image/svg+xml'},
        ],
        apple: [
            {url: '/apple-touch-icon.png', sizes: '180x180'},
        ],
    },
    manifest: '/site.webmanifest',
    appleWebApp: {
        title: 'AI Paraphrasing Tool',
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin="anonymous" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
            <link
                rel="preload"
                as="style"
                href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
            />

            <noscript>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
                />
            </noscript>
        </head>
        <body className={inter.className}>
        <MuiThemeProvider>
            {children}
        </MuiThemeProvider>
        </body>
        </html>
    );
}
